### PR TITLE
Enable automatic monthly uploads of new works to Figshare (Loughborough repository)

### PR DESCRIPTION
**Pull request by rhigman**
Extends existing automated dissemination logic.

Ideally we want to avoid attempting to upload works which were already uploaded in previous batches. This would show up as a failure on the Actions dashboard, and the more "benign" failures we get, the more likely we are to miss genuine failures.

For IA, it's easy to find the full set of existing uploads and filter them out beforehand. Figshare doesn't provide this ability. For Crossref (where re-uploads don't matter anyway), a record's eligibility for upload is based on its last update timestamp, so we can reliably filter for anything updated since the last run. However, here, we ideally want to find "all works which were published since the last run". Since "time of publication" isn't automatically recorded in the database in the same way as "time of last update", we can't rely on strict date/time cutoffs.

The solution chosen is to search for everything marked as Active with a publication date within the previous calendar month (for a monthly upload schedule), but to only do this search a few days after the start of the month. This minimises potential issues to do with timezones, datelines, daylight savings, and (above all) publishers not getting around to updating a work's Thoth record until a day or so after its actual publication date.

Our ultimate goal (as previously discussed) is to implement a mechanism for triggering automated dissemination as soon as a work is set to Active. This would be the most reliable way to avoid such issues.

### CODE REVIEW

**Review by ja573 — COMMENTED** [review]
Is there really no way to find already uploaded books in figshare? Do they not get an ID of some sort when first uploaded?

It's fairly common for publishers to update books after publication, and so it would be good to be able to update the corresponding records

**Comment by rhigman** [comment]
> Is there really no way to find already uploaded books in figshare? Do they not get an ID of some sort when first uploaded?
> 
> It's fairly common for publishers to update books after publication, and so it would be good to be able to update the corresponding records

It's possible to check whether an individual book has already been uploaded to Figshare, and this is done within the `disseminator` program itself (which is what would cause the unwanted failure in the Actions dashboard): https://github.com/thoth-pub/thoth-dissemination/blob/d137ad2f6a6eaefc57e39763b17637969755b0ec/fsuploader.py#L48-L53
The same failsafe also exists for Internet Archive: https://github.com/thoth-pub/thoth-dissemination/blob/d137ad2f6a6eaefc57e39763b17637969755b0ec/iauploader.py#L34-L40

However, what's not possible in Figshare is an equivalent of this: https://github.com/thoth-pub/thoth-dissemination/blob/d137ad2f6a6eaefc57e39763b17637969755b0ec/obtain_new_ids.py#L159-L164

Agree that updating would be good, and it will be possible to implement further down the line, using the Figshare search to find the specific book as above.

**Comment by rhigman** [comment]
> > > Is there really no way to find already uploaded books in figshare? Do they not get an ID of some sort when first uploaded?
> > > It's fairly common for publishers to update books after publication, and so it would be good to be able to update the corresponding records
> > 
> > 
> > It's possible to check whether an individual book has already been uploaded to Figshare, and this is done within the `disseminator` program itself (which is what would cause the unwanted failure in the Actions dashboard):
[snip]
> > Agree that updating would be good, and it will be possible to implement further down the line, using the Figshare search to find the specific book as above.
> 
> In that case I don't see the need to exit the program when attempting to upload a record that has already been uploaded previously. You could just log it as a warning and skip it (since it's at that point – when checking if the record already exists – that we'd implement updating the record)

Just for clarity, the `disseminator` program runs once per record. So exiting the program already equates to skipping that record and moving on to the next one. The change you're suggesting is just to log the skip as a warning rather than a failure. Is there an advantage to doing this? The GitHub Actions dashboard makes warnings very easy to overlook.

**Comment by ja573** [comment]
> > > > Is there really no way to find already uploaded books in figshare? Do they not get an ID of some sort when first uploaded?
> > > > It's fairly common for publishers to update books after publication, and so it would be good to be able to update the corresponding records
> > > 
> > > 
> > > It's possible to check whether an individual book has already been uploaded to Figshare, and this is done within the `disseminator` program itself (which is what would cause the unwanted failure in the Actions dashboard):
> > > [snip]
> > > Agree that updating would be good, and it will be possible to implement further down the line, using the Figshare search to find the specific book as above.
> > 
> > 
> > In that case I don't see the need to exit the program when attempting to upload a record that has already been uploaded previously. You could just log it as a warning and skip it (since it's at that point – when checking if the record already exists – that we'd implement updating the record)
> 
> Just for clarity, the `disseminator` program runs once per record. So exiting the program already equates to skipping that record and moving on to the next one. The change you're suggesting is just to log the skip as a warning rather than a failure. Is there an advantage to doing this? The GitHub Actions dashboard makes warnings very easy to overlook.

Oh, I see. I was getting confused by:

> Ideally we want to avoid attempting to upload works which were already uploaded in previous batches. This would show up as a failure on the Actions dashboard, and the more "benign" failures we get, the more likely we are to miss genuine failures.

**Review by ja573 — DISMISSED** [review]

**Pull request merged**
